[package]
name = "cargo-godot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cargo_metadata = "0.18"
serde_json = "1.0"
thiserror = "1.0"
which = "6.0"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
